// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/proto/towerbell.proto

package towerbell;

public final class Proto {
  private Proto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FixedConfigOrBuilder extends
      // @@protoc_insertion_point(interface_extends:towerbell.FixedConfig)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string database_path = 1;</code>
     * @return Whether the databasePath field is set.
     */
    boolean hasDatabasePath();
    /**
     * <code>optional string database_path = 1;</code>
     * @return The databasePath.
     */
    java.lang.String getDatabasePath();
    /**
     * <code>optional string database_path = 1;</code>
     * @return The bytes for databasePath.
     */
    com.google.protobuf.ByteString
        getDatabasePathBytes();

    /**
     * <pre>
     * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
     * </pre>
     *
     * <code>optional string gpio_label = 2;</code>
     * @return Whether the gpioLabel field is set.
     */
    boolean hasGpioLabel();
    /**
     * <pre>
     * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
     * </pre>
     *
     * <code>optional string gpio_label = 2;</code>
     * @return The gpioLabel.
     */
    java.lang.String getGpioLabel();
    /**
     * <pre>
     * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
     * </pre>
     *
     * <code>optional string gpio_label = 2;</code>
     * @return The bytes for gpioLabel.
     */
    com.google.protobuf.ByteString
        getGpioLabelBytes();

    /**
     * <code>optional int32 server_port = 3;</code>
     * @return Whether the serverPort field is set.
     */
    boolean hasServerPort();
    /**
     * <code>optional int32 server_port = 3;</code>
     * @return The serverPort.
     */
    int getServerPort();

    /**
     * <pre>
     * Enables PC testing
     * </pre>
     *
     * <code>optional bool disable_native = 4;</code>
     * @return Whether the disableNative field is set.
     */
    boolean hasDisableNative();
    /**
     * <pre>
     * Enables PC testing
     * </pre>
     *
     * <code>optional bool disable_native = 4;</code>
     * @return The disableNative.
     */
    boolean getDisableNative();

    /**
     * <code>optional string template_directory = 5;</code>
     * @return Whether the templateDirectory field is set.
     */
    boolean hasTemplateDirectory();
    /**
     * <code>optional string template_directory = 5;</code>
     * @return The templateDirectory.
     */
    java.lang.String getTemplateDirectory();
    /**
     * <code>optional string template_directory = 5;</code>
     * @return The bytes for templateDirectory.
     */
    com.google.protobuf.ByteString
        getTemplateDirectoryBytes();

    /**
     * <code>optional string static_file_directory = 6;</code>
     * @return Whether the staticFileDirectory field is set.
     */
    boolean hasStaticFileDirectory();
    /**
     * <code>optional string static_file_directory = 6;</code>
     * @return The staticFileDirectory.
     */
    java.lang.String getStaticFileDirectory();
    /**
     * <code>optional string static_file_directory = 6;</code>
     * @return The bytes for staticFileDirectory.
     */
    com.google.protobuf.ByteString
        getStaticFileDirectoryBytes();

    /**
     * <code>optional bool development_mode = 7;</code>
     * @return Whether the developmentMode field is set.
     */
    boolean hasDevelopmentMode();
    /**
     * <code>optional bool development_mode = 7;</code>
     * @return The developmentMode.
     */
    boolean getDevelopmentMode();

    /**
     * <code>optional int32 gpio_logical_pin = 8;</code>
     * @return Whether the gpioLogicalPin field is set.
     */
    boolean hasGpioLogicalPin();
    /**
     * <code>optional int32 gpio_logical_pin = 8;</code>
     * @return The gpioLogicalPin.
     */
    int getGpioLogicalPin();

    /**
     * <code>optional string ringer_classname = 9;</code>
     * @return Whether the ringerClassname field is set.
     */
    boolean hasRingerClassname();
    /**
     * <code>optional string ringer_classname = 9;</code>
     * @return The ringerClassname.
     */
    java.lang.String getRingerClassname();
    /**
     * <code>optional string ringer_classname = 9;</code>
     * @return The bytes for ringerClassname.
     */
    com.google.protobuf.ByteString
        getRingerClassnameBytes();
  }
  /**
   * <pre>
   * Configuration that the web interface cannot modify.
   * </pre>
   *
   * Protobuf type {@code towerbell.FixedConfig}
   */
  public static final class FixedConfig extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:towerbell.FixedConfig)
      FixedConfigOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FixedConfig.newBuilder() to construct.
    private FixedConfig(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FixedConfig() {
      databasePath_ = "";
      gpioLabel_ = "";
      templateDirectory_ = "";
      staticFileDirectory_ = "";
      ringerClassname_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FixedConfig();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return towerbell.Proto.internal_static_towerbell_FixedConfig_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return towerbell.Proto.internal_static_towerbell_FixedConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              towerbell.Proto.FixedConfig.class, towerbell.Proto.FixedConfig.Builder.class);
    }

    private int bitField0_;
    public static final int DATABASE_PATH_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object databasePath_ = "";
    /**
     * <code>optional string database_path = 1;</code>
     * @return Whether the databasePath field is set.
     */
    @java.lang.Override
    public boolean hasDatabasePath() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string database_path = 1;</code>
     * @return The databasePath.
     */
    @java.lang.Override
    public java.lang.String getDatabasePath() {
      java.lang.Object ref = databasePath_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          databasePath_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string database_path = 1;</code>
     * @return The bytes for databasePath.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDatabasePathBytes() {
      java.lang.Object ref = databasePath_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        databasePath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GPIO_LABEL_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object gpioLabel_ = "";
    /**
     * <pre>
     * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
     * </pre>
     *
     * <code>optional string gpio_label = 2;</code>
     * @return Whether the gpioLabel field is set.
     */
    @java.lang.Override
    public boolean hasGpioLabel() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <pre>
     * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
     * </pre>
     *
     * <code>optional string gpio_label = 2;</code>
     * @return The gpioLabel.
     */
    @java.lang.Override
    public java.lang.String getGpioLabel() {
      java.lang.Object ref = gpioLabel_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          gpioLabel_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
     * </pre>
     *
     * <code>optional string gpio_label = 2;</code>
     * @return The bytes for gpioLabel.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGpioLabelBytes() {
      java.lang.Object ref = gpioLabel_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gpioLabel_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVER_PORT_FIELD_NUMBER = 3;
    private int serverPort_ = 0;
    /**
     * <code>optional int32 server_port = 3;</code>
     * @return Whether the serverPort field is set.
     */
    @java.lang.Override
    public boolean hasServerPort() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional int32 server_port = 3;</code>
     * @return The serverPort.
     */
    @java.lang.Override
    public int getServerPort() {
      return serverPort_;
    }

    public static final int DISABLE_NATIVE_FIELD_NUMBER = 4;
    private boolean disableNative_ = false;
    /**
     * <pre>
     * Enables PC testing
     * </pre>
     *
     * <code>optional bool disable_native = 4;</code>
     * @return Whether the disableNative field is set.
     */
    @java.lang.Override
    public boolean hasDisableNative() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <pre>
     * Enables PC testing
     * </pre>
     *
     * <code>optional bool disable_native = 4;</code>
     * @return The disableNative.
     */
    @java.lang.Override
    public boolean getDisableNative() {
      return disableNative_;
    }

    public static final int TEMPLATE_DIRECTORY_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object templateDirectory_ = "";
    /**
     * <code>optional string template_directory = 5;</code>
     * @return Whether the templateDirectory field is set.
     */
    @java.lang.Override
    public boolean hasTemplateDirectory() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional string template_directory = 5;</code>
     * @return The templateDirectory.
     */
    @java.lang.Override
    public java.lang.String getTemplateDirectory() {
      java.lang.Object ref = templateDirectory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          templateDirectory_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string template_directory = 5;</code>
     * @return The bytes for templateDirectory.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTemplateDirectoryBytes() {
      java.lang.Object ref = templateDirectory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        templateDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATIC_FILE_DIRECTORY_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object staticFileDirectory_ = "";
    /**
     * <code>optional string static_file_directory = 6;</code>
     * @return Whether the staticFileDirectory field is set.
     */
    @java.lang.Override
    public boolean hasStaticFileDirectory() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string static_file_directory = 6;</code>
     * @return The staticFileDirectory.
     */
    @java.lang.Override
    public java.lang.String getStaticFileDirectory() {
      java.lang.Object ref = staticFileDirectory_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          staticFileDirectory_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string static_file_directory = 6;</code>
     * @return The bytes for staticFileDirectory.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStaticFileDirectoryBytes() {
      java.lang.Object ref = staticFileDirectory_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        staticFileDirectory_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DEVELOPMENT_MODE_FIELD_NUMBER = 7;
    private boolean developmentMode_ = false;
    /**
     * <code>optional bool development_mode = 7;</code>
     * @return Whether the developmentMode field is set.
     */
    @java.lang.Override
    public boolean hasDevelopmentMode() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>optional bool development_mode = 7;</code>
     * @return The developmentMode.
     */
    @java.lang.Override
    public boolean getDevelopmentMode() {
      return developmentMode_;
    }

    public static final int GPIO_LOGICAL_PIN_FIELD_NUMBER = 8;
    private int gpioLogicalPin_ = 0;
    /**
     * <code>optional int32 gpio_logical_pin = 8;</code>
     * @return Whether the gpioLogicalPin field is set.
     */
    @java.lang.Override
    public boolean hasGpioLogicalPin() {
      return ((bitField0_ & 0x00000080) != 0);
    }
    /**
     * <code>optional int32 gpio_logical_pin = 8;</code>
     * @return The gpioLogicalPin.
     */
    @java.lang.Override
    public int getGpioLogicalPin() {
      return gpioLogicalPin_;
    }

    public static final int RINGER_CLASSNAME_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private volatile java.lang.Object ringerClassname_ = "";
    /**
     * <code>optional string ringer_classname = 9;</code>
     * @return Whether the ringerClassname field is set.
     */
    @java.lang.Override
    public boolean hasRingerClassname() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>optional string ringer_classname = 9;</code>
     * @return The ringerClassname.
     */
    @java.lang.Override
    public java.lang.String getRingerClassname() {
      java.lang.Object ref = ringerClassname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ringerClassname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ringer_classname = 9;</code>
     * @return The bytes for ringerClassname.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRingerClassnameBytes() {
      java.lang.Object ref = ringerClassname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ringerClassname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, databasePath_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, gpioLabel_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeInt32(3, serverPort_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeBool(4, disableNative_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, templateDirectory_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, staticFileDirectory_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeBool(7, developmentMode_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        output.writeInt32(8, gpioLogicalPin_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, ringerClassname_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, databasePath_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, gpioLabel_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, serverPort_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, disableNative_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, templateDirectory_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, staticFileDirectory_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, developmentMode_);
      }
      if (((bitField0_ & 0x00000080) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, gpioLogicalPin_);
      }
      if (((bitField0_ & 0x00000100) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, ringerClassname_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof towerbell.Proto.FixedConfig)) {
        return super.equals(obj);
      }
      towerbell.Proto.FixedConfig other = (towerbell.Proto.FixedConfig) obj;

      if (hasDatabasePath() != other.hasDatabasePath()) return false;
      if (hasDatabasePath()) {
        if (!getDatabasePath()
            .equals(other.getDatabasePath())) return false;
      }
      if (hasGpioLabel() != other.hasGpioLabel()) return false;
      if (hasGpioLabel()) {
        if (!getGpioLabel()
            .equals(other.getGpioLabel())) return false;
      }
      if (hasServerPort() != other.hasServerPort()) return false;
      if (hasServerPort()) {
        if (getServerPort()
            != other.getServerPort()) return false;
      }
      if (hasDisableNative() != other.hasDisableNative()) return false;
      if (hasDisableNative()) {
        if (getDisableNative()
            != other.getDisableNative()) return false;
      }
      if (hasTemplateDirectory() != other.hasTemplateDirectory()) return false;
      if (hasTemplateDirectory()) {
        if (!getTemplateDirectory()
            .equals(other.getTemplateDirectory())) return false;
      }
      if (hasStaticFileDirectory() != other.hasStaticFileDirectory()) return false;
      if (hasStaticFileDirectory()) {
        if (!getStaticFileDirectory()
            .equals(other.getStaticFileDirectory())) return false;
      }
      if (hasDevelopmentMode() != other.hasDevelopmentMode()) return false;
      if (hasDevelopmentMode()) {
        if (getDevelopmentMode()
            != other.getDevelopmentMode()) return false;
      }
      if (hasGpioLogicalPin() != other.hasGpioLogicalPin()) return false;
      if (hasGpioLogicalPin()) {
        if (getGpioLogicalPin()
            != other.getGpioLogicalPin()) return false;
      }
      if (hasRingerClassname() != other.hasRingerClassname()) return false;
      if (hasRingerClassname()) {
        if (!getRingerClassname()
            .equals(other.getRingerClassname())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasDatabasePath()) {
        hash = (37 * hash) + DATABASE_PATH_FIELD_NUMBER;
        hash = (53 * hash) + getDatabasePath().hashCode();
      }
      if (hasGpioLabel()) {
        hash = (37 * hash) + GPIO_LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getGpioLabel().hashCode();
      }
      if (hasServerPort()) {
        hash = (37 * hash) + SERVER_PORT_FIELD_NUMBER;
        hash = (53 * hash) + getServerPort();
      }
      if (hasDisableNative()) {
        hash = (37 * hash) + DISABLE_NATIVE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDisableNative());
      }
      if (hasTemplateDirectory()) {
        hash = (37 * hash) + TEMPLATE_DIRECTORY_FIELD_NUMBER;
        hash = (53 * hash) + getTemplateDirectory().hashCode();
      }
      if (hasStaticFileDirectory()) {
        hash = (37 * hash) + STATIC_FILE_DIRECTORY_FIELD_NUMBER;
        hash = (53 * hash) + getStaticFileDirectory().hashCode();
      }
      if (hasDevelopmentMode()) {
        hash = (37 * hash) + DEVELOPMENT_MODE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getDevelopmentMode());
      }
      if (hasGpioLogicalPin()) {
        hash = (37 * hash) + GPIO_LOGICAL_PIN_FIELD_NUMBER;
        hash = (53 * hash) + getGpioLogicalPin();
      }
      if (hasRingerClassname()) {
        hash = (37 * hash) + RINGER_CLASSNAME_FIELD_NUMBER;
        hash = (53 * hash) + getRingerClassname().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static towerbell.Proto.FixedConfig parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static towerbell.Proto.FixedConfig parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static towerbell.Proto.FixedConfig parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static towerbell.Proto.FixedConfig parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static towerbell.Proto.FixedConfig parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static towerbell.Proto.FixedConfig parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static towerbell.Proto.FixedConfig parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static towerbell.Proto.FixedConfig parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static towerbell.Proto.FixedConfig parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static towerbell.Proto.FixedConfig parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static towerbell.Proto.FixedConfig parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static towerbell.Proto.FixedConfig parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(towerbell.Proto.FixedConfig prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Configuration that the web interface cannot modify.
     * </pre>
     *
     * Protobuf type {@code towerbell.FixedConfig}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:towerbell.FixedConfig)
        towerbell.Proto.FixedConfigOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return towerbell.Proto.internal_static_towerbell_FixedConfig_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return towerbell.Proto.internal_static_towerbell_FixedConfig_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                towerbell.Proto.FixedConfig.class, towerbell.Proto.FixedConfig.Builder.class);
      }

      // Construct using towerbell.Proto.FixedConfig.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        databasePath_ = "";
        gpioLabel_ = "";
        serverPort_ = 0;
        disableNative_ = false;
        templateDirectory_ = "";
        staticFileDirectory_ = "";
        developmentMode_ = false;
        gpioLogicalPin_ = 0;
        ringerClassname_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return towerbell.Proto.internal_static_towerbell_FixedConfig_descriptor;
      }

      @java.lang.Override
      public towerbell.Proto.FixedConfig getDefaultInstanceForType() {
        return towerbell.Proto.FixedConfig.getDefaultInstance();
      }

      @java.lang.Override
      public towerbell.Proto.FixedConfig build() {
        towerbell.Proto.FixedConfig result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public towerbell.Proto.FixedConfig buildPartial() {
        towerbell.Proto.FixedConfig result = new towerbell.Proto.FixedConfig(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(towerbell.Proto.FixedConfig result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.databasePath_ = databasePath_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.gpioLabel_ = gpioLabel_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.serverPort_ = serverPort_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.disableNative_ = disableNative_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.templateDirectory_ = templateDirectory_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.staticFileDirectory_ = staticFileDirectory_;
          to_bitField0_ |= 0x00000020;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.developmentMode_ = developmentMode_;
          to_bitField0_ |= 0x00000040;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.gpioLogicalPin_ = gpioLogicalPin_;
          to_bitField0_ |= 0x00000080;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.ringerClassname_ = ringerClassname_;
          to_bitField0_ |= 0x00000100;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof towerbell.Proto.FixedConfig) {
          return mergeFrom((towerbell.Proto.FixedConfig)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(towerbell.Proto.FixedConfig other) {
        if (other == towerbell.Proto.FixedConfig.getDefaultInstance()) return this;
        if (other.hasDatabasePath()) {
          databasePath_ = other.databasePath_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasGpioLabel()) {
          gpioLabel_ = other.gpioLabel_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasServerPort()) {
          setServerPort(other.getServerPort());
        }
        if (other.hasDisableNative()) {
          setDisableNative(other.getDisableNative());
        }
        if (other.hasTemplateDirectory()) {
          templateDirectory_ = other.templateDirectory_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasStaticFileDirectory()) {
          staticFileDirectory_ = other.staticFileDirectory_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (other.hasDevelopmentMode()) {
          setDevelopmentMode(other.getDevelopmentMode());
        }
        if (other.hasGpioLogicalPin()) {
          setGpioLogicalPin(other.getGpioLogicalPin());
        }
        if (other.hasRingerClassname()) {
          ringerClassname_ = other.ringerClassname_;
          bitField0_ |= 0x00000100;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                databasePath_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                gpioLabel_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                serverPort_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 32: {
                disableNative_ = input.readBool();
                bitField0_ |= 0x00000008;
                break;
              } // case 32
              case 42: {
                templateDirectory_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                staticFileDirectory_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 56: {
                developmentMode_ = input.readBool();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 64: {
                gpioLogicalPin_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              case 74: {
                ringerClassname_ = input.readBytes();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object databasePath_ = "";
      /**
       * <code>optional string database_path = 1;</code>
       * @return Whether the databasePath field is set.
       */
      public boolean hasDatabasePath() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string database_path = 1;</code>
       * @return The databasePath.
       */
      public java.lang.String getDatabasePath() {
        java.lang.Object ref = databasePath_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            databasePath_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string database_path = 1;</code>
       * @return The bytes for databasePath.
       */
      public com.google.protobuf.ByteString
          getDatabasePathBytes() {
        java.lang.Object ref = databasePath_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          databasePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string database_path = 1;</code>
       * @param value The databasePath to set.
       * @return This builder for chaining.
       */
      public Builder setDatabasePath(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        databasePath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>optional string database_path = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDatabasePath() {
        databasePath_ = getDefaultInstance().getDatabasePath();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>optional string database_path = 1;</code>
       * @param value The bytes for databasePath to set.
       * @return This builder for chaining.
       */
      public Builder setDatabasePathBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        databasePath_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object gpioLabel_ = "";
      /**
       * <pre>
       * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
       * </pre>
       *
       * <code>optional string gpio_label = 2;</code>
       * @return Whether the gpioLabel field is set.
       */
      public boolean hasGpioLabel() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <pre>
       * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
       * </pre>
       *
       * <code>optional string gpio_label = 2;</code>
       * @return The gpioLabel.
       */
      public java.lang.String getGpioLabel() {
        java.lang.Object ref = gpioLabel_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            gpioLabel_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
       * </pre>
       *
       * <code>optional string gpio_label = 2;</code>
       * @return The bytes for gpioLabel.
       */
      public com.google.protobuf.ByteString
          getGpioLabelBytes() {
        java.lang.Object ref = gpioLabel_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gpioLabel_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
       * </pre>
       *
       * <code>optional string gpio_label = 2;</code>
       * @param value The gpioLabel to set.
       * @return This builder for chaining.
       */
      public Builder setGpioLabel(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        gpioLabel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
       * </pre>
       *
       * <code>optional string gpio_label = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGpioLabel() {
        gpioLabel_ = getDefaultInstance().getGpioLabel();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Device label for GPIO controller.  Use "pinctrl-bcm2711" for Raspberry PI.
       * </pre>
       *
       * <code>optional string gpio_label = 2;</code>
       * @param value The bytes for gpioLabel to set.
       * @return This builder for chaining.
       */
      public Builder setGpioLabelBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        gpioLabel_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private int serverPort_ ;
      /**
       * <code>optional int32 server_port = 3;</code>
       * @return Whether the serverPort field is set.
       */
      @java.lang.Override
      public boolean hasServerPort() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional int32 server_port = 3;</code>
       * @return The serverPort.
       */
      @java.lang.Override
      public int getServerPort() {
        return serverPort_;
      }
      /**
       * <code>optional int32 server_port = 3;</code>
       * @param value The serverPort to set.
       * @return This builder for chaining.
       */
      public Builder setServerPort(int value) {
        
        serverPort_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 server_port = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerPort() {
        bitField0_ = (bitField0_ & ~0x00000004);
        serverPort_ = 0;
        onChanged();
        return this;
      }

      private boolean disableNative_ ;
      /**
       * <pre>
       * Enables PC testing
       * </pre>
       *
       * <code>optional bool disable_native = 4;</code>
       * @return Whether the disableNative field is set.
       */
      @java.lang.Override
      public boolean hasDisableNative() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <pre>
       * Enables PC testing
       * </pre>
       *
       * <code>optional bool disable_native = 4;</code>
       * @return The disableNative.
       */
      @java.lang.Override
      public boolean getDisableNative() {
        return disableNative_;
      }
      /**
       * <pre>
       * Enables PC testing
       * </pre>
       *
       * <code>optional bool disable_native = 4;</code>
       * @param value The disableNative to set.
       * @return This builder for chaining.
       */
      public Builder setDisableNative(boolean value) {
        
        disableNative_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Enables PC testing
       * </pre>
       *
       * <code>optional bool disable_native = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDisableNative() {
        bitField0_ = (bitField0_ & ~0x00000008);
        disableNative_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object templateDirectory_ = "";
      /**
       * <code>optional string template_directory = 5;</code>
       * @return Whether the templateDirectory field is set.
       */
      public boolean hasTemplateDirectory() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional string template_directory = 5;</code>
       * @return The templateDirectory.
       */
      public java.lang.String getTemplateDirectory() {
        java.lang.Object ref = templateDirectory_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            templateDirectory_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string template_directory = 5;</code>
       * @return The bytes for templateDirectory.
       */
      public com.google.protobuf.ByteString
          getTemplateDirectoryBytes() {
        java.lang.Object ref = templateDirectory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          templateDirectory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string template_directory = 5;</code>
       * @param value The templateDirectory to set.
       * @return This builder for chaining.
       */
      public Builder setTemplateDirectory(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        templateDirectory_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional string template_directory = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTemplateDirectory() {
        templateDirectory_ = getDefaultInstance().getTemplateDirectory();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>optional string template_directory = 5;</code>
       * @param value The bytes for templateDirectory to set.
       * @return This builder for chaining.
       */
      public Builder setTemplateDirectoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        templateDirectory_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object staticFileDirectory_ = "";
      /**
       * <code>optional string static_file_directory = 6;</code>
       * @return Whether the staticFileDirectory field is set.
       */
      public boolean hasStaticFileDirectory() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string static_file_directory = 6;</code>
       * @return The staticFileDirectory.
       */
      public java.lang.String getStaticFileDirectory() {
        java.lang.Object ref = staticFileDirectory_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            staticFileDirectory_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string static_file_directory = 6;</code>
       * @return The bytes for staticFileDirectory.
       */
      public com.google.protobuf.ByteString
          getStaticFileDirectoryBytes() {
        java.lang.Object ref = staticFileDirectory_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          staticFileDirectory_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string static_file_directory = 6;</code>
       * @param value The staticFileDirectory to set.
       * @return This builder for chaining.
       */
      public Builder setStaticFileDirectory(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        staticFileDirectory_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional string static_file_directory = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearStaticFileDirectory() {
        staticFileDirectory_ = getDefaultInstance().getStaticFileDirectory();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>optional string static_file_directory = 6;</code>
       * @param value The bytes for staticFileDirectory to set.
       * @return This builder for chaining.
       */
      public Builder setStaticFileDirectoryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        staticFileDirectory_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private boolean developmentMode_ ;
      /**
       * <code>optional bool development_mode = 7;</code>
       * @return Whether the developmentMode field is set.
       */
      @java.lang.Override
      public boolean hasDevelopmentMode() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional bool development_mode = 7;</code>
       * @return The developmentMode.
       */
      @java.lang.Override
      public boolean getDevelopmentMode() {
        return developmentMode_;
      }
      /**
       * <code>optional bool development_mode = 7;</code>
       * @param value The developmentMode to set.
       * @return This builder for chaining.
       */
      public Builder setDevelopmentMode(boolean value) {
        
        developmentMode_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool development_mode = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearDevelopmentMode() {
        bitField0_ = (bitField0_ & ~0x00000040);
        developmentMode_ = false;
        onChanged();
        return this;
      }

      private int gpioLogicalPin_ ;
      /**
       * <code>optional int32 gpio_logical_pin = 8;</code>
       * @return Whether the gpioLogicalPin field is set.
       */
      @java.lang.Override
      public boolean hasGpioLogicalPin() {
        return ((bitField0_ & 0x00000080) != 0);
      }
      /**
       * <code>optional int32 gpio_logical_pin = 8;</code>
       * @return The gpioLogicalPin.
       */
      @java.lang.Override
      public int getGpioLogicalPin() {
        return gpioLogicalPin_;
      }
      /**
       * <code>optional int32 gpio_logical_pin = 8;</code>
       * @param value The gpioLogicalPin to set.
       * @return This builder for chaining.
       */
      public Builder setGpioLogicalPin(int value) {
        
        gpioLogicalPin_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 gpio_logical_pin = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearGpioLogicalPin() {
        bitField0_ = (bitField0_ & ~0x00000080);
        gpioLogicalPin_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object ringerClassname_ = "";
      /**
       * <code>optional string ringer_classname = 9;</code>
       * @return Whether the ringerClassname field is set.
       */
      public boolean hasRingerClassname() {
        return ((bitField0_ & 0x00000100) != 0);
      }
      /**
       * <code>optional string ringer_classname = 9;</code>
       * @return The ringerClassname.
       */
      public java.lang.String getRingerClassname() {
        java.lang.Object ref = ringerClassname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            ringerClassname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ringer_classname = 9;</code>
       * @return The bytes for ringerClassname.
       */
      public com.google.protobuf.ByteString
          getRingerClassnameBytes() {
        java.lang.Object ref = ringerClassname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ringerClassname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ringer_classname = 9;</code>
       * @param value The ringerClassname to set.
       * @return This builder for chaining.
       */
      public Builder setRingerClassname(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ringerClassname_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ringer_classname = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearRingerClassname() {
        ringerClassname_ = getDefaultInstance().getRingerClassname();
        bitField0_ = (bitField0_ & ~0x00000100);
        onChanged();
        return this;
      }
      /**
       * <code>optional string ringer_classname = 9;</code>
       * @param value The bytes for ringerClassname to set.
       * @return This builder for chaining.
       */
      public Builder setRingerClassnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        ringerClassname_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:towerbell.FixedConfig)
    }

    // @@protoc_insertion_point(class_scope:towerbell.FixedConfig)
    private static final towerbell.Proto.FixedConfig DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new towerbell.Proto.FixedConfig();
    }

    public static towerbell.Proto.FixedConfig getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<FixedConfig>
        PARSER = new com.google.protobuf.AbstractParser<FixedConfig>() {
      @java.lang.Override
      public FixedConfig parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<FixedConfig> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FixedConfig> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public towerbell.Proto.FixedConfig getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_towerbell_FixedConfig_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_towerbell_FixedConfig_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031src/proto/towerbell.proto\022\ttowerbell\"\356" +
      "\001\n\013FixedConfig\022\025\n\rdatabase_path\030\001 \001(\t\022\022\n" +
      "\ngpio_label\030\002 \001(\t\022\023\n\013server_port\030\003 \001(\005\022\026" +
      "\n\016disable_native\030\004 \001(\010\022\032\n\022template_direc" +
      "tory\030\005 \001(\t\022\035\n\025static_file_directory\030\006 \001(" +
      "\t\022\030\n\020development_mode\030\007 \001(\010\022\030\n\020gpio_logi" +
      "cal_pin\030\010 \001(\005\022\030\n\020ringer_classname\030\t \001(\tB" +
      "\022\n\ttowerbellB\005Proto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_towerbell_FixedConfig_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_towerbell_FixedConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_towerbell_FixedConfig_descriptor,
        new java.lang.String[] { "DatabasePath", "GpioLabel", "ServerPort", "DisableNative", "TemplateDirectory", "StaticFileDirectory", "DevelopmentMode", "GpioLogicalPin", "RingerClassname", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
