/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class towerbell_pi_physical_GPIOChipInfoProvider */

#ifndef _Included_towerbell_pi_physical_GPIOChipInfoProvider
#define _Included_towerbell_pi_physical_GPIOChipInfoProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     towerbell_pi_physical_GPIOChipInfoProvider
 * Method:    getGPIOChipInfoInternal
 * Signature: (Ljava/lang/String;)Ltowerbell/pi/physical/GPIOChipInfoProvider/GPIOChipInfo;
 */
JNIEXPORT jobject JNICALL Java_towerbell_pi_physical_GPIOChipInfoProvider_getGPIOChipInfoInternal
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
