/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class towerbell_pi_physical_GPIOController */

#ifndef _Included_towerbell_pi_physical_GPIOController
#define _Included_towerbell_pi_physical_GPIOController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     towerbell_pi_physical_GPIOController
 * Method:    initializeOutput
 * Signature: (Ljava/lang/String;IZ)J
 */
JNIEXPORT jlong JNICALL Java_towerbell_pi_physical_GPIOController_initializeOutput
  (JNIEnv *, jobject, jstring, jint, jboolean);

/*
 * Class:     towerbell_pi_physical_GPIOController
 * Method:    initializeInput
 * Signature: (Ljava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_towerbell_pi_physical_GPIOController_initializeInput
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     towerbell_pi_physical_GPIOController
 * Method:    setInternal
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_towerbell_pi_physical_GPIOController_setInternal
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     towerbell_pi_physical_GPIOController
 * Method:    getInternal
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_towerbell_pi_physical_GPIOController_getInternal
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
